version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./infra:/infra
      - ./hello-world:/infra/hello-world
      - terraform-data:/infra/.terraform
    working_dir: /infra
    entrypoint: /infra/bootstrap/terraform/entrypoint.sh
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

  localstack:
    container_name: localstack
    environment:
      - SERVICES=iam,lambda,cloudwatch,apigateway,s3
      - DEBUG=1
      - HOSTNAME_EXTERNAL=localhost
      - HOSTNAME=0.0.0.0
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    image: localstack/localstack:1.0
    ports:
      - "4566-4599:4566-4599"
      - "8055:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/tmp/localstack

volumes:
  terraform-data:
    name:   terraform-data
  localstack-data:
    name: localstack-data